### ISSUE TITLE
Error listing Go versions

### ISSUE THREAD

**Issue by n-r-w** [anativ/vscode-go-version-switcher#1]
When trying to select "Go Version Switcher," an error "Error listing Go versions" appears. 
The standard "Choose Go environment" function works fine.
VSCode version 1.92.0

**Comment by khan-yin** [comment]
> When trying to select "Go Version Switcher," an error "Error listing Go versions" appears. The standard "Choose Go environment" function works fine. VSCode version 1.92.0

Did you solve the problem? I have the same problem with you.

**Comment by khan-yin** [comment]
![Image](https://github.com/user-attachments/assets/146a2c15-3b63-4999-a4d0-ed4138e58896)

![Image](https://github.com/user-attachments/assets/b2e33e30-be78-45dc-a25d-420e74adc92a)

I have already solved it. It caused by nodejs `exec()` func in `extension.js`, this function uses `/bin/sh` shell by default. so we need to add `gvm` commond for environment value in `.profile` or `.shrc`:
```shell
echo '. ~/.gvm/scripts/gvm' >> ~/.profile
```
